/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttributeRow: typeof import('./src/components/AttributeRow.vue')['default']
    AttributeRowAdd: typeof import('./src/components/AttributeRowAdd.vue')['default']
    BaseRow: typeof import('./src/components/BaseRow.vue')['default']
    BuiltInAttrs: typeof import('./src/components/BuiltInAttrs.vue')['default']
    DbAttrs: typeof import('./src/components/DbAttrs.vue')['default']
    DbRow: typeof import('./src/components/DbRow.vue')['default']
    DebugInfo: typeof import('./src/components/DebugInfo.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDatePicker: typeof import('tdesign-vue-next')['DatePicker']
    TDateRangePicker: typeof import('tdesign-vue-next')['DateRangePicker']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TOption: typeof import('tdesign-vue-next')['Option']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}

// For TSX support
declare global {
  const AttributeRow: typeof import('./src/components/AttributeRow.vue')['default']
  const AttributeRowAdd: typeof import('./src/components/AttributeRowAdd.vue')['default']
  const BaseRow: typeof import('./src/components/BaseRow.vue')['default']
  const BuiltInAttrs: typeof import('./src/components/BuiltInAttrs.vue')['default']
  const DbAttrs: typeof import('./src/components/DbAttrs.vue')['default']
  const DbRow: typeof import('./src/components/DbRow.vue')['default']
  const DebugInfo: typeof import('./src/components/DebugInfo.vue')['default']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TCard: typeof import('tdesign-vue-next')['Card']
  const TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TDatePicker: typeof import('tdesign-vue-next')['DatePicker']
  const TDateRangePicker: typeof import('tdesign-vue-next')['DateRangePicker']
  const TFooter: typeof import('tdesign-vue-next')['Footer']
  const TIcon: typeof import('tdesign-vue-next')['Icon']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TMenu: typeof import('tdesign-vue-next')['Menu']
  const TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
  const TOption: typeof import('tdesign-vue-next')['Option']
  const TSelect: typeof import('tdesign-vue-next')['Select']
  const TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
  const TTabs: typeof import('tdesign-vue-next')['Tabs']
  const TTag: typeof import('tdesign-vue-next')['Tag']
}