/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddToDatabaseDialog: typeof import('./../components/AddToDatabaseDialog.vue')['default']
    AttributeRow: typeof import('./../components/AttributeRow.vue')['default']
    AttributeRowActions: typeof import('./../components/AttributeRowActions.vue')['default']
    AttributeRowAdd: typeof import('./../components/AttributeRowAdd.vue')['default']
    AvFieldRow: typeof import('./../components/av/AvFieldRow.vue')['default']
    BaseRow: typeof import('./../components/BaseRow.vue')['default']
    BuiltInAttrs: typeof import('./../components/BuiltInAttrs.vue')['default']
    DebugInfo: typeof import('./../components/DebugInfo.vue')['default']
    FieldSettingsDialog: typeof import('./../components/FieldSettingsDialog.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TInput: typeof import('tdesign-vue-next')['Input']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
  }
}

// For TSX support
declare global {
  const AddToDatabaseDialog: typeof import('./../components/AddToDatabaseDialog.vue')['default']
  const AttributeRow: typeof import('./../components/AttributeRow.vue')['default']
  const AttributeRowActions: typeof import('./../components/AttributeRowActions.vue')['default']
  const AttributeRowAdd: typeof import('./../components/AttributeRowAdd.vue')['default']
  const AvFieldRow: typeof import('./../components/av/AvFieldRow.vue')['default']
  const BaseRow: typeof import('./../components/BaseRow.vue')['default']
  const BuiltInAttrs: typeof import('./../components/BuiltInAttrs.vue')['default']
  const DebugInfo: typeof import('./../components/DebugInfo.vue')['default']
  const FieldSettingsDialog: typeof import('./../components/FieldSettingsDialog.vue')['default']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
  const TDialog: typeof import('tdesign-vue-next')['Dialog']
  const TForm: typeof import('tdesign-vue-next')['Form']
  const TFormItem: typeof import('tdesign-vue-next')['FormItem']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TSelect: typeof import('tdesign-vue-next')['Select']
  const TTextarea: typeof import('tdesign-vue-next')['Textarea']
}