/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttributeRow: typeof import('./../components/AttributeRow.vue')['default']
    AttributeRowActions: typeof import('./../components/AttributeRowActions.vue')['default']
    AttributeRowAdd: typeof import('./../components/AttributeRowAdd.vue')['default']
    BaseRow: typeof import('./../components/BaseRow.vue')['default']
    BuiltInAttrs: typeof import('./../components/BuiltInAttrs.vue')['default']
    DebugInfo: typeof import('./../components/DebugInfo.vue')['default']
    FieldSettingsDialog: typeof import('./../components/FieldSettingsDialog.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TDatePicker: typeof import('tdesign-vue-next')['DatePicker']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTagInput: typeof import('tdesign-vue-next')['TagInput']
  }
}

// For TSX support
declare global {
  const AttributeRow: typeof import('./../components/AttributeRow.vue')['default']
  const AttributeRowActions: typeof import('./../components/AttributeRowActions.vue')['default']
  const AttributeRowAdd: typeof import('./../components/AttributeRowAdd.vue')['default']
  const BaseRow: typeof import('./../components/BaseRow.vue')['default']
  const BuiltInAttrs: typeof import('./../components/BuiltInAttrs.vue')['default']
  const DebugInfo: typeof import('./../components/DebugInfo.vue')['default']
  const FieldSettingsDialog: typeof import('./../components/FieldSettingsDialog.vue')['default']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TCard: typeof import('tdesign-vue-next')['Card']
  const TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
  const TDatePicker: typeof import('tdesign-vue-next')['DatePicker']
  const TIcon: typeof import('tdesign-vue-next')['Icon']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
  const TLoading: typeof import('tdesign-vue-next')['Loading']
  const TOption: typeof import('tdesign-vue-next')['Option']
  const TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
  const TSelect: typeof import('tdesign-vue-next')['Select']
  const TSwitch: typeof import('tdesign-vue-next')['Switch']
  const TTagInput: typeof import('tdesign-vue-next')['TagInput']
}